server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

  jpa:
    show-sql: true
    database: mysql
    # 스크립트 자동 생성을 끄는 역할. 기존에 이미 읽혀진(생성된) 데이터베이스를 사용할 떄 씀
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true